"""model gateway and chat: catalog, installations, instances, leases, chat, llm usage.

Owner: Akshay Sunil Navani (Person 2). Reviewed and merged by Nikhil Hiro Ghind (Person 1).

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 01:01:41.163925+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('day', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('holder_type', sa.Text(), nullable=False),
    sa.Column('holder_id', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index('ix_llm_usage_day_provider', 'llm_usage', ['day', 'provider'], unique=False)
    op.create_index('ix_llm_usage_holder', 'llm_usage', ['holder_type', 'holder_id'], unique=False)
    op.create_table('model_catalog',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('family', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('backend', sa.Text(), nullable=False),
    sa.Column('profile', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('expected_memory_bytes', sa.BigInteger(), nullable=False),
    sa.Column('context_limit', sa.Integer(), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('trust_state', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_catalog'))
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('model_profile', sa.Text(), nullable=False),
    sa.Column('knowledge_base_id', sa.UUID(), nullable=True),
    sa.Column('retrieval_mode', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('active_lease_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("retrieval_mode IN ('when_relevant', 'only_knowledge')", name=op.f('ck_chat_sessions_mode')),
    sa.ForeignKeyConstraint(['model_profile'], ['model_catalog.id'], name=op.f('fk_chat_sessions_model_profile_model_catalog')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('model_installations',
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('revision', sa.Text(), nullable=True),
    sa.Column('disk_path', sa.Text(), nullable=True),
    sa.Column('bytes_done', sa.BigInteger(), nullable=False),
    sa.Column('bytes_total', sa.BigInteger(), nullable=True),
    sa.Column('current_file', sa.Text(), nullable=True),
    sa.Column('checksum', sa.Text(), nullable=True),
    sa.Column('error', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('license_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('NOT_INSTALLED', 'DOWNLOADING', 'INSTALLED', 'DOWNLOAD_ERROR', 'DELETING')", name=op.f('ck_model_installations_state')),
    sa.ForeignKeyConstraint(['model_id'], ['model_catalog.id'], name=op.f('fk_model_installations_model_id_model_catalog'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', name=op.f('pk_model_installations'))
    )
    op.create_table('model_instances',
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('drain_reason', sa.Text(), nullable=True),
    sa.Column('endpoint', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('reserved_bytes', sa.BigInteger(), nullable=False),
    sa.Column('observed', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('load_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idle_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("drain_reason IS NULL OR drain_reason IN ('idle', 'manual', 'stopping')", name=op.f('ck_model_instances_drain')),
    sa.CheckConstraint("state IN ('NOT_LOADED', 'LOADING', 'READY', 'DRAINING', 'LOAD_ERROR', 'RUNTIME_ERROR')", name=op.f('ck_model_instances_state')),
    sa.ForeignKeyConstraint(['model_id'], ['model_catalog.id'], name=op.f('fk_model_instances_model_id_model_catalog'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', name=op.f('pk_model_instances'))
    )
    op.create_table('model_leases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('holder_type', sa.Text(), nullable=False),
    sa.Column('holder_id', sa.Text(), nullable=False),
    sa.Column('holder_label', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("holder_type IN ('run', 'chat', 'manual')", name=op.f('ck_model_leases_holder_type')),
    sa.ForeignKeyConstraint(['model_id'], ['model_catalog.id'], name=op.f('fk_model_leases_model_id_model_catalog'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_leases'))
    )
    op.create_index('ix_model_leases_active', 'model_leases', ['model_id'], unique=False, postgresql_where=sa.text('released_at IS NULL'))
    op.create_index('uq_model_leases_active_holder', 'model_leases', ['model_id', 'holder_type', 'holder_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('usage', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_chat_messages_role')),
    sa.CheckConstraint("status IN ('streaming', 'complete', 'stopped', 'failed')", name=op.f('ck_chat_messages_status')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('uq_model_leases_active_holder', table_name='model_leases', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index('ix_model_leases_active', table_name='model_leases', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_table('model_leases')
    op.drop_table('model_instances')
    op.drop_table('model_installations')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('model_catalog')
    op.drop_index('ix_llm_usage_holder', table_name='llm_usage')
    op.drop_index('ix_llm_usage_day_provider', table_name='llm_usage')
    op.drop_table('llm_usage')
    # ### end Alembic commands ###
