"""secrets, connectors, and knowledge: encrypted secrets, provider profiles, OAuth
connections, telephony calls, knowledge bases, documents, and document chunks.

Owner: Nikhil Sajan Khaneja (Person 3). Reviewed and merged by Nikhil Hiro Ghind (Person 1).
The broker also appends to ``audit_events`` and references ``agent_runs``; the knowledge
service owns ``document_chunks`` (exact cosine search; PLAN.md defers the HNSW index).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 08:09:29.651945+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encrypted_secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('owner_type', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('google', 'twilio', 'openai', 'anthropic')", name=op.f('ck_encrypted_secrets_provider')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encrypted_secrets')),
    sa.UniqueConstraint('owner_type', 'owner_id', name=op.f('uq_encrypted_secrets_owner_type_owner_id'))
    )
    op.create_table('knowledge_bases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('embedding_profile', sa.Text(), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_knowledge_bases_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_bases')),
    sa.UniqueConstraint('owner_id', 'name', name=op.f('uq_knowledge_bases_owner_id_name'))
    )
    op.create_index(op.f('ix_knowledge_bases_owner_id'), 'knowledge_bases', ['owner_id'], unique=False)
    op.create_table('oauth_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_subject', sa.Text(), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('encrypted_secret_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('google')", name=op.f('ck_oauth_connections_provider')),
    sa.CheckConstraint("status IN ('CONNECTED', 'NEEDS_ATTENTION')", name=op.f('ck_oauth_connections_status')),
    sa.ForeignKeyConstraint(['encrypted_secret_id'], ['encrypted_secrets.id'], name=op.f('fk_oauth_connections_encrypted_secret_id_encrypted_secrets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_connections')),
    sa.UniqueConstraint('user_id', 'provider', 'provider_subject', name=op.f('uq_oauth_connections_user_id_provider_provider_subject'))
    )
    op.create_table('provider_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('encrypted_secret_id', sa.UUID(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_models', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budgets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('google', 'twilio', 'openai', 'anthropic')", name=op.f('ck_provider_profiles_provider')),
    sa.CheckConstraint("status IN ('UNTESTED', 'CONNECTED', 'ERROR')", name=op.f('ck_provider_profiles_status')),
    sa.ForeignKeyConstraint(['encrypted_secret_id'], ['encrypted_secrets.id'], name=op.f('fk_provider_profiles_encrypted_secret_id_encrypted_secrets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_provider_profiles_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_profiles')),
    sa.UniqueConstraint('owner_id', 'provider', 'display_name', name=op.f('uq_provider_profiles_owner_id_provider_display_name'))
    )
    op.create_index(op.f('ix_provider_profiles_owner_id'), 'provider_profiles', ['owner_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('bytes', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('PENDING', 'PROCESSING', 'READY', 'FAILED')", name=op.f('ck_documents_state')),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_documents_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('kb_id', 'sha256', name=op.f('uq_documents_kb_id_sha256'))
    )
    op.create_index(op.f('ix_documents_kb_id'), 'documents', ['kb_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', Vector(512), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'ordinal', name=op.f('uq_document_chunks_document_id_ordinal'))
    )
    op.create_table('telephony_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('provider_sid', sa.Text(), nullable=True),
    sa.Column('destination_hash', sa.Text(), nullable=False),
    sa.Column('destination_last4', sa.Text(), nullable=False),
    sa.Column('disclosure', sa.Text(), nullable=False),
    sa.Column('script', sa.Text(), nullable=False),
    sa.Column('response_seconds', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_telephony_calls_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telephony_calls')),
    sa.UniqueConstraint('provider_sid', name=op.f('uq_telephony_calls_provider_sid')),
    sa.UniqueConstraint('run_id', 'idempotency_key', name=op.f('uq_telephony_calls_run_id_idempotency_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telephony_calls')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_documents_kb_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_provider_profiles_owner_id'), table_name='provider_profiles')
    op.drop_table('provider_profiles')
    op.drop_table('oauth_connections')
    op.drop_index(op.f('ix_knowledge_bases_owner_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_table('encrypted_secrets')
    # ### end Alembic commands ###
