"""control plane core: identity, catalog, runs, inputs, schedules, jobs, audit.

Also enables pgvector for the knowledge service and adds database-enforced
immutability for agent_versions and append-only audit_events.

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 11:17:55.939037+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_catalog_entries',
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('current_version', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('trust_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('bundled', 'imported')", name=op.f('ck_agent_catalog_entries_source')),
    sa.CheckConstraint("trust_status IN ('curated', 'imported_unreviewed')", name=op.f('ck_agent_catalog_entries_trust_status')),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agent_catalog_entries'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=True),
    sa.Column('target_id', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('user', 'system', 'service', 'anonymous')", name=op.f('ck_audit_events_actor')),
    sa.CheckConstraint("outcome IN ('success', 'denied', 'failure')", name=op.f('ck_audit_events_outcome')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.Text(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('last_error', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('available', 'claimed', 'succeeded', 'dead', 'cancelled')", name=op.f('ck_jobs_state')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_available', 'jobs', ['available_at', 'id'], unique=False, postgresql_where=sa.text("state = 'available'"))
    op.create_index('ix_jobs_claimed_lease', 'jobs', ['lease_until'], unique=False, postgresql_where=sa.text("state = 'claimed'"))
    op.create_index('uq_jobs_live_dedupe', 'jobs', ['dedupe_key'], unique=True, postgresql_where=sa.text("dedupe_key IS NOT NULL AND state IN ('available', 'claimed')"))
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('username_normalized', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name=op.f('ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username_normalized', name=op.f('uq_users_username_normalized'))
    )
    op.create_table('agent_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('manifest', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('image_ref', sa.Text(), nullable=False),
    sa.Column('image_digest', sa.Text(), nullable=False),
    sa.Column('sdk_protocol', sa.Text(), nullable=False),
    sa.Column('architectures', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_catalog_entries.agent_id'], name=op.f('fk_agent_versions_agent_id_agent_catalog_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_versions')),
    sa.UniqueConstraint('agent_id', 'version', name=op.f('uq_agent_versions_agent_id_version'))
    )
    op.create_table('idempotency_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_records_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('user_id', 'key', name=op.f('uq_idempotency_records_user_id_key'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_settings_updated_by_users')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('agent_installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('approved_version_id', sa.UUID(), nullable=True),
    sa.Column('config', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('approved_permissions', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('model_bindings', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('needs_reapproval', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_catalog_entries.agent_id'], name=op.f('fk_agent_installations_agent_id_agent_catalog_entries')),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_agent_installations_agent_version_id_agent_versions')),
    sa.ForeignKeyConstraint(['approved_version_id'], ['agent_versions.id'], name=op.f('fk_agent_installations_approved_version_id_agent_versions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_installations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_installations'))
    )
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('cron', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('misfire_policy', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("misfire_policy IN ('fire_once', 'skip')", name=op.f('ck_schedules_misfire_policy')),
    sa.ForeignKeyConstraint(['installation_id'], ['agent_installations.id'], name=op.f('fk_schedules_installation_id_agent_installations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index('ix_schedules_due', 'schedules', ['next_run_at'], unique=False, postgresql_where=sa.text('enabled AND deleted_at IS NULL'))
    op.create_index(op.f('ix_schedules_installation_id'), 'schedules', ['installation_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('state_entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_attempt', sa.Integer(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('permissions_snapshot', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('model_bindings', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('active_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_input_wait_seconds', sa.Integer(), nullable=False),
    sa.Column('active_seconds_used', sa.Float(), nullable=False),
    sa.Column('input_wait_seconds_used', sa.Float(), nullable=False),
    sa.Column('result', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('QUEUED', 'PREPARING', 'LOADING_MODEL', 'RUNNING', 'WAITING_INPUT', 'CANCELLING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'INTERRUPTED')", name=op.f('ck_agent_runs_state')),
    sa.CheckConstraint("trigger IN ('manual', 'schedule')", name=op.f('ck_agent_runs_trigger')),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_agent_runs_agent_version_id_agent_versions')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agent_runs_created_by_users')),
    sa.ForeignKeyConstraint(['installation_id'], ['agent_installations.id'], name=op.f('fk_agent_runs_installation_id_agent_installations')),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_agent_runs_schedule_id_schedules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_installation_id'), 'agent_runs', ['installation_id'], unique=False)
    op.create_index('ix_agent_runs_state', 'agent_runs', ['state'], unique=False)
    op.create_index('uq_agent_runs_schedule_occurrence', 'agent_runs', ['schedule_id', 'scheduled_for'], unique=True, postgresql_where=sa.text('schedule_id IS NOT NULL'))
    op.create_table('idempotency_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('claimed', 'in_doubt', 'completed')", name=op.f('ck_idempotency_actions_state')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_idempotency_actions_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_actions')),
    sa.UniqueConstraint('run_id', 'key', name=op.f('uq_idempotency_actions_run_id_key'))
    )
    op.create_table('input_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('schema', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('preview', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('answer', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('answered_by', sa.UUID(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('pending', 'answered', 'cancelled', 'expired')", name=op.f('ck_input_requests_state')),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], name=op.f('fk_input_requests_answered_by_users')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_input_requests_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_input_requests')),
    sa.UniqueConstraint('run_id', 'key', name=op.f('uq_input_requests_run_id_key'))
    )
    op.create_index('ix_input_requests_pending', 'input_requests', ['state'], unique=False, postgresql_where=sa.text("state = 'pending'"))
    op.create_table('run_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('runtime_ref', sa.Text(), nullable=True),
    sa.Column('capability_token_id', sa.Text(), nullable=True),
    sa.Column('heartbeat_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('starting', 'running', 'exited', 'interrupted', 'cancelled')", name=op.f('ck_run_attempts_state')),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_run_attempts_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_attempts')),
    sa.UniqueConstraint('run_id', 'attempt', name=op.f('uq_run_attempts_run_id_attempt'))
    )
    op.create_table('run_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_run_events_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_events')),
    sa.UniqueConstraint('run_id', 'sequence', name=op.f('uq_run_events_run_id_sequence'))
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION cq_reject_modification() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION '% rows are immutable (% rejected)', TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER agent_versions_immutable BEFORE UPDATE ON agent_versions "
        "FOR EACH ROW EXECUTE FUNCTION cq_reject_modification()"
    )
    op.execute(
        "CREATE TRIGGER audit_events_append_only BEFORE UPDATE OR DELETE ON audit_events "
        "FOR EACH ROW EXECUTE FUNCTION cq_reject_modification()"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_events')
    op.drop_table('run_attempts')
    op.drop_index('ix_input_requests_pending', table_name='input_requests', postgresql_where=sa.text("state = 'pending'"))
    op.drop_table('input_requests')
    op.drop_table('idempotency_actions')
    op.drop_index('uq_agent_runs_schedule_occurrence', table_name='agent_runs', postgresql_where=sa.text('schedule_id IS NOT NULL'))
    op.drop_index('ix_agent_runs_state', table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_installation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_schedules_installation_id'), table_name='schedules')
    op.drop_index('ix_schedules_due', table_name='schedules', postgresql_where=sa.text('enabled AND deleted_at IS NULL'))
    op.drop_table('schedules')
    op.drop_table('agent_installations')
    op.drop_table('settings')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('idempotency_records')
    op.drop_table('agent_versions')
    op.drop_table('users')
    op.drop_index('uq_jobs_live_dedupe', table_name='jobs', postgresql_where=sa.text("dedupe_key IS NOT NULL AND state IN ('available', 'claimed')"))
    op.drop_index('ix_jobs_claimed_lease', table_name='jobs', postgresql_where=sa.text("state = 'claimed'"))
    op.drop_index('ix_jobs_available', table_name='jobs', postgresql_where=sa.text("state = 'available'"))
    op.drop_table('jobs')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('agent_catalog_entries')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS cq_reject_modification()")
